Add sign out
mashakiselyova/TestProject pull request #1
Opened 2021-02-15 09:31 UTC by mashakiselyova

2021-02-15 10:40 UTC, shaeredal requested changes

2021-02-15 10:40 UTC, shaeredal commented on TestProject.BL/Services/UserService.cs
> +            return new UserLoginModel
use mappers

2021-02-15 10:40 UTC, shaeredal commented on TestProject.BL/Services/UserService.cs
>          {
btw, the separate method is not needed here, you can just call repository.

2021-02-15 10:40 UTC, shaeredal commented on TestProject/ClientApp/src/components/Login.js
> +        window.location.pathname = '/account/google-login';
use `useHistory` or `Link` from `react-router-dom`.

2021-02-15 10:40 UTC, shaeredal commented on TestProject/ClientApp/src/components/Login.js
> +class Login extends React.Component {
use functional components

2021-02-15 10:40 UTC, shaeredal commented on TestProject/ClientApp/src/components/Login.js
> +        this.setState({ name: data.firstName + ' ' + data.lastName });
use `useState` hook.

2021-02-15 10:40 UTC, shaeredal commented on TestProject/ClientApp/src/components/Login.js
> +    async componentDidMount() {
`useEffect` hook

2021-02-15 10:40 UTC, shaeredal commented on TestProject/ClientApp/src/components/Login.js
> +        if (this.state.name === undefined) {
```suggestion
        this.state.name
        ? // option 1
        : // option 2
```

2021-02-15 10:40 UTC, shaeredal commented on TestProject/Controllers/AccountController.cs
> +                return null;
you should throw unauthorized exception in case user is not authorized.

2021-02-15 10:40 UTC, shaeredal commented on TestProject/Controllers/AccountController.cs
> +            var result = await HttpContext.AuthenticateAsync(CookieAuthenticationDefaults.AuthenticationScheme);
you can use authorization attribute

2021-02-15 15:10 UTC, shaeredal requested changes

2021-02-15 15:10 UTC, dd221x0 commented on TestProject/ClientApp/src/components/Main.js
> +    });
add `[]` as a dependencies list, it will fetch on every re-render otherwise

2021-02-15 15:10 UTC, shaeredal commented on TestProject/Controllers/AccountController.cs
> +    [Authorize, Route("account")]
it's better to split into separate attributes

2021-02-15 15:10 UTC, shaeredal commented on TestProject/Controllers/AccountController.cs
> +            var claims = result.Principal?.Identities.FirstOrDefault().Claims;
you don't need re-authenticate user to get claims, try using `this.User`.

2021-02-15 15:10 UTC, shaeredal commented on TestProject/Controllers/AccountController.cs
> +            var result = await HttpContext.AuthenticateAsync(CookieAuthenticationDefaults.AuthenticationScheme);
`result` - is a bad name, btw

2021-02-15 15:10 UTC, shaeredal commented on TestProject/Controllers/AccountController.cs
> +            if (claims != null)
this check is not needed in case user authenticated, that should be checked by auth filter.

2021-02-16 09:12 UTC, shaeredal requested changes

2021-02-16 09:12 UTC, shaeredal commented on TestProject/ClientApp/src/components/Header.js
> +                        {props.name === undefined
` === undefined` part is redundant here

2021-02-16 09:12 UTC, shaeredal commented on TestProject/ClientApp/src/components/Header.js
> +                        {props.name === undefined
`name` is not the parameter that responsible for whether the user is authorized or not, you shouldn't rely on it here

2021-02-16 09:18 UTC, shaeredal requested changes

2021-02-16 09:18 UTC, shaeredal commented on TestProject/ClientApp/src/components/UserProfile.js
> +            const response = await fetch("/account/getUserProfile");
you should handle errors here, e.g. 401

2021-02-17 09:25 UTC, shaeredal approved these changes

2021-02-17 09:25 UTC, shaeredal commented on TestProject/Controllers/AccountController.cs
> +        //[Route("getUserProfile")]
🤔

2021-02-17 09:25 UTC, shaeredal commented on TestProject/Startup.cs
> +        public IConfiguration Configuration { get; set; }
nit: `set` should be private

2021-02-17 09:27 UTC, mashakiselyova commented on TestProject/Controllers/AccountController.cs
> +        //[Route("getUserProfile")]
oops)

2021-02-17 09:31 UTC, shaeredal commented on TestProject/ClientApp/src/components/Header.js
> +                        {!props.userLoggedIn
Try not to use negated conditions

2021-02-17 09:33 UTC, shaeredal commented on TestProject/ClientApp/src/components/Layout.js
> +            .then(function (response) {
```suggestion
            .then((response) => {
```
using lambda is more elegant

2021-02-17 10:49 UTC, DmitryDanilovich requested changes

2021-02-17 10:49 UTC, DmitryDanilovich commented on TestProject.BL/Services/UserService.cs
> +        private bool CheckUserForChanges(UserLoginModel userLoginModel, User user)
Name of methods that return `bool` should be a question that return value answers.
`HasCanged()` for example.

2021-02-17 10:49 UTC, DmitryDanilovich commented on TestProject.BL/Services/UserService.cs
> +            _userRepo = repo;
don't spare letters, `Repository` is not a long word

2021-02-17 10:49 UTC, DmitryDanilovich commented on TestProject.BL/Services/UserService.cs
>              return userLoginModel;
what is the point of returning the same model that we passed to the method?

2021-02-17 10:49 UTC, DmitryDanilovich commented on TestProject.BL/Services/UserService.cs
> +                }
extract to `Update()`

2021-02-17 10:49 UTC, DmitryDanilovich commented on TestProject.BL/Services/UserService.cs
> +                await _userRepo.CreateAsync(user);
Extract to `Create()`

2021-02-17 10:49 UTC, DmitryDanilovich commented on TestProject.DAL/Repositories/IRepository.cs
> +        void Update(T t);
what is the point of making one of the methods `async` and an other not?

2021-02-17 10:49 UTC, DmitryDanilovich commented on TestProject.BL/Services/UserService.cs
> +            return UserMapper.MapUserToUserProfile(user);
it will throw NRE in case `user == null`

2021-02-17 12:12 UTC, DmitryDanilovich commented on TestProject.BL/Services/UserService.cs
> +                }
extract to `Update()` x2

2021-02-17 12:25 UTC, merged