Add post page
mashakiselyova/TestProject pull request #12
Opened 2021-03-30 12:27 UTC by mashakiselyova

2021-03-30 13:55 UTC, shaeredal requested changes

2021-03-30 13:55 UTC, dd221x0 commented on TestProject.BL/Mappers/RichPostMapper.cs
> +                Author = new Author
You can create a separate `User` <-> `Author` mapper and use here

2021-03-30 13:55 UTC, shaeredal commented on TestProject/ClientApp/src/components/Layout.js
> +    async function handleGetUpdatedRating(postId) {
`handle` is superfluous here

2021-03-30 13:55 UTC, shaeredal commented on TestProject/ClientApp/src/components/Layout.js
> +    async function handleGetUpdatedRating(postId) {
and this shouldn't be placed here, you can create a separate service for such a requests

2021-03-30 13:55 UTC, shaeredal commented on TestProject/Controllers/PostController.cs
> +                User.Identity.IsAuthenticated ? User.GetEmail() : null));
don't make such a complex expressions, extract variables
📝

2021-03-30 13:55 UTC, shaeredal commented on TestProject/ClientApp/src/components/Posts.js
> +    async function handleUpdateRating(postId) {
`handle` is not needed here as well

2021-03-30 13:55 UTC, shaeredal commented on TestProject/ClientApp/src/components/PostPage.js
> +        createDate: "",
it definitely should not be set to empty string

2021-03-30 13:58 UTC, shaeredal commented on TestProject.BL.Test/Services/PostServiceTests.cs
> +        public void If_rich_post_does_not_exist_should_throw_exception()
nit: Should_throw_exception_when_requesting_rich_post_that_does_not_exist

2021-03-31 14:00 UTC, shaeredal commented on TestProject/ClientApp/src/components/Layout.js
> +    //async function handleGetUpdatedRating(postId) {
what is this?

2021-03-31 14:02 UTC, mashakiselyova commented on TestProject/ClientApp/src/components/Layout.js
> +    //async function handleGetUpdatedRating(postId) {
oops

2021-03-31 14:03 UTC, shaeredal commented on TestProject/ClientApp/src/services/RatingService.js
> +﻿export default async function getRating(postId) {
why it is default export?

2021-03-31 14:08 UTC, shaeredal commented on TestProject/ClientApp/src/components/PostPage.js
> +    const [post, setPost] = useState(undefined);
You never need to set `undefined`, it is default value. It's better use an empty object in this case.

2021-03-31 14:19 UTC, merged